Controllers/BrandController.cs
using DoQuocHuy0352.Context;
using System.Linq;
using System.Web.Mvc;

namespace DoQuocHuy0352.Controllers
{
    public class BrandController : Controller
    {
        private readonly WebsiteEcomEntities1 _context;

        // Constructor để khởi tạo context
        public BrandController()
        {
            _context = new WebsiteEcomEntities1();
        }

        // Action để hiển thị tất cả các thương hiệu
        public ActionResult Index()
        {
            // Lấy danh sách tất cả các thương hiệu
            var brands = _context.Brands.ToList();
            return View(brands);
        }

        // Action để hiển thị các sản phẩm theo thương hiệu cụ thể
        public ActionResult ProductByBrand(int brandId)
        {
            // Lấy thông tin thương hiệu và các sản phẩm liên quan
            var brand = _context.Brands.Find(brandId);
            if (brand == null)
            {
                return HttpNotFound();
            }

            var products = _context.Products.Where(p => p.BrandId == brandId).ToList();

            // Truyền dữ liệu sang View
            ViewBag.Brand = brand;
            return View(products);
        }
    }
}

Controllers/CategoriesController.cs
using DoQuocHuy0352.Context;
using Microsoft.Ajax.Utilities;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

public class CategoriesController : Controller
{
    private WebsiteEcomEntities1 _context = new WebsiteEcomEntities1();
    public ActionResult Index()
    {
        var categories = _context.Categories.ToList();
        return View(categories);
    }

    public ActionResult Index1()
    {
        var listCat = _context.Products
            .Select(p => p.Category)
            .Distinct()
            .ToList();
        return View(listCat);
    }

    public ActionResult Details(int id)
    {
        var category = _context.Categories.Find(id);
        if (category == null)
        {
            return HttpNotFound();
        }
        return View(category);
    }

    public ActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(Category category)
    {
        if (ModelState.IsValid)
        {
            _context.Categories.Add(category);
            _context.SaveChanges();
            return RedirectToAction("Categories1");
        }
        return View(category);
    }

    public ActionResult Edit(int id)
    {
        var category = _context.Categories.Find(id);
        if (category == null)
        {
            return HttpNotFound();
        }
        return View(category);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(Category category)
    {
        if (ModelState.IsValid)
        {
            _context.Entry(category).State = EntityState.Modified;
            _context.SaveChanges();
            return RedirectToAction("Categories1");
        }
        return View(category);
    }

    public ActionResult Delete(int id)
    {
        var category = _context.Categories.Find(id);
        if (category == null)
        {
            return HttpNotFound();
        }
        return View(category);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int id)
    {
        var category = _context.Categories.Find(id);
        _context.Categories.Remove(category);
        _context.SaveChanges();
        return RedirectToAction("Categories1");
    }

    public ActionResult ProductsByCategory(int categoryId)
    {
        var products = _context.Products
            .Where(p => p.CategoryId == categoryId)
            .ToList();

        if (!products.Any())
        {
            return HttpNotFound("No products found for this category.");
        }

        ViewBag.CategoryId = categoryId; // Optional: if you want to use it in the view
        return View(products);
    }

}

Controllers/ProductController.cs
using DoQuocHuy0352.Context;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

public class ProductController : Controller
{
    private WebsiteEcomEntities1 _context = new WebsiteEcomEntities1();

    public ActionResult Index()
    {
        var listProduct = _context.Products.ToList();
        return View(listProduct);
    }


    public ActionResult ProductDetail(int id)
    {
        var product = _context.Products.FirstOrDefault(p => p.Id == id);
        if (product == null)
        {
            return HttpNotFound();
        }
        return View(product);
    }

    public async Task<ActionResult> ProductsByCategory(int categoryId)
    {
        var products = await _context.Products
            .Where(p => p.CategoryId == categoryId)
            .ToListAsync();

        ViewBag.CategoryId = categoryId;
        return View(products);
    }
}

Controllers/ProfileController.cs
using System.Linq;
using System.Web.Mvc;
using DoQuocHuy0352.Context;

namespace DoQuocHuy0352.Controllers
{
    public class ProfileController : Controller
    {
        private WebsiteEcomEntities1 _context;

        public ProfileController()
        {
            _context = new WebsiteEcomEntities1();
        }

        // GET: Profile/Index
        public ActionResult Index()
        {
            var email = Session["username"] as string;
            if (string.IsNullOrEmpty(email))
            {
                return RedirectToAction("Login", "User");
            }

            var user = _context.Users.FirstOrDefault(u => u.Email == email);
            if (user == null)
            {
                return RedirectToAction("Login", "User");
            }

            return View(user);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="cache-control" content="max-age=604800" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Website title - bootstrap html template</title>

    <link href="~/images/favicon.ico" rel="shortcut icon" type="image/x-icon">

    <!-- jQuery -->
    <script src="~/js/jquery-2.0.0.min.js" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="~/js/bootstrap.bundle.min.js" type="text/javascript"></script>
    <link href="~/css/bootstrap.css" rel="stylesheet" type="text/css" />

    <!-- Font awesome 5 -->
    <link href="~/fonts/fontawesome/css/all.min.css" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="~/css/ui.css" rel="stylesheet" type="text/css" />
    <link href="~/css/responsive.css" rel="stylesheet" type="text/css" />

    <!-- custom javascript -->
    <script src="~/js/script.js" type="text/javascript"></script>
</head>
<body>
    <header class="section-header">
        <section class="header-main border-bottom">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-2 col-lg-3 col-md-12">
                        <a href="@Url.Action("Index", "Home")" class="brand-wrap">
                            <img class="logo" src="~/images/logo.png">
                        </a> <!-- brand-wrap.// -->
                    </div>
                    <div class="col-xl-6 col-lg-5 col-md-6">
                        <form action="#" class="search-header">
                            <div class="input-group w-100">
                                <select class="custom-select border-right" name="category_name">
                                    <option value="">All type</option>
                                    <option value="codex">Special</option>
                                    <option value="comments">Only best</option>
                                    <option value="content">Latest</option>
                                </select>
                                <input type="text" class="form-control" placeholder="Search">

                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit">
                                        <i class="fa fa-search"></i> Search
                                    </button>
                                </div>
                            </div>
                        </form> <!-- search-wrap .end// -->
                    </div> <!-- col.// -->
                    <div class="col-xl-4 col-lg-4 col-md-6">
                        <div class="widgets-wrap float-md-right">
                            <div class="widget-header mr-3">
                                <a href="@Url.Action("Index", "Profile")" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-user"></i>
                                        <span class="notify">
                                            @if (Session["isLoggedIn"] != null && (bool)Session["isLoggedIn"])
                                            {
                                                @:1
                                            }
                                            else
                                            {
                                                @:0
                                            }
                                        </span>
                                    </div>
                                    <small class="text">My profile</small>
                                </a>
                            </div>


                            <div class="widget-header mr-3">
                                <a href="#" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-comment-dots"></i>
                                        <span class="notify">1</span>
                                    </div>
                                    <small class="text"> Message </small>
                                </a>
                            </div>
                            <div class="widget-header mr-3">
                                <a href="#" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-store"></i>
                                    </div>
                                    <small class="text"> Orders </small>
                                </a>
                            </div>

                            <div class="widget-header">
                                <a href="@Url.Action("Index", "Cart")" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-shopping-cart"></i>
                                    </div>
                                    <small class="text"> Cart </small>
                                </a>
                            </div>
                            <div class="widget-header mr-3">
                                <a href="@Url.Action("index", "Admin", new { area = "Admin" })" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-user-shield"></i>
                                    </div>
                                    <small class="text"> Admin </small>
                                </a>
                            </div>

                            <div class="widget-header mr-3">
                                <a href="@Url.Action("Login", "User")" class="widget-view">
                                    <div class="icon-area">
                                        <i class="fa fa-sign-in-alt"></i>
                                    </div>
                                    <small class="text"> Login </small>
                                </a>
                            </div>
                        </div> <!-- widgets-wrap.// -->
                    </div> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- container.// -->
        </section> <!-- header-main .// -->


        <nav class="navbar navbar-main navbar-expand-lg border-bottom">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="main_nav">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="@Url.Action("Index", "Product")"></i> Product </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"> Categories </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="@Url.Action("Index", "Categories")">All</a>
                                <a class="dropdown-item" href="#">Machinery</a>
                                <a class="dropdown-item" href="#">Electronics</a>
                                <a class="dropdown-item" href="#">Home textile</a>
                                <a class="dropdown-item" href="#">Home and kitchen</a>
                                <a class="dropdown-item" href="#">Service and equipment</a>
                                <a class="dropdown-item" href="#">Healthcare items</a>
                                <a class="dropdown-item" href="#">Toys and Hobbies</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index", "Brand")">Brand</a>
                        </li>

                    </ul>
                    <ul class="navbar-nav ml-md-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Get the app</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="http://example.com" data-toggle="dropdown">English</a>
                            <div class="dropdown-menu dropdown-menu-right">
                                <a class="dropdown-item" href="#">Russian</a>
                                <a class="dropdown-item" href="#">French</a>
                                <a class="dropdown-item" href="#">Spanish</a>
                                <a class="dropdown-item" href="#">Chinese</a>
                            </div>
                        </li>
                    </ul>
                </div> <!-- collapse .// -->
            </div> <!-- container .// -->
        </nav>
    </header> <!-- section-header.// -->

    @RenderBody()

    <footer class="section-footer bg-secondary">
        <div class="container">
            <section class="footer-top padding-y-lg text-white">
                <div class="row">
                    <aside class="col-md col-6">
                        <h6 class="title">Brands</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Adidas</a></li>
                            <li> <a href="#">Puma</a></li>
                            <li> <a href="#">Reebok</a></li>
                            <li> <a href="#">Nike</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Company</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">About us</a></li>
                            <li> <a href="#">Career</a></li>
                            <li> <a href="#">Find a store</a></li>
                            <li> <a href="#">Rules and terms</a></li>
                            <li> <a href="#">Sitemap</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Help</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#">Contact us</a></li>
                            <li> <a href="#">Money refund</a></li>
                            <li> <a href="#">Order status</a></li>
                            <li> <a href="#">Shipping info</a></li>
                            <li> <a href="#">Open dispute</a></li>
                        </ul>
                    </aside>
                    <aside class="col-md col-6">
                        <h6 class="title">Account</h6>
                        <ul class="list-unstyled">
                            <li> <a href="#"> User Login </a></li>
                            <li> <a href="#"> User register </a></li>
                            <li> <a href="#"> Account Setting </a></li>
                            <li> <a href="#"> My Orders </a></li>
                        </ul>
                    </aside>
                    <aside class="col-md">
                        <h6 class="title">Social</h6>
                        <ul class="list-unstyled">
                            <li><a href="#"> <i class="fab fa-facebook"></i> Facebook </a></li>
                            <li><a href="#"> <i class="fab fa-twitter"></i> Twitter </a></li>
                            <li><a href="#"> <i class="fab fa-instagram"></i> Instagram </a></li>
                            <li><a href="#"> <i class="fab fa-youtube"></i> Youtube </a></li>
                        </ul>
                    </aside>
                </div> <!-- row.// -->
            </section>	<!-- footer-top.// -->

            <section class="footer-bottom text-center">

                <p class="text-white">Privacy Policy - Terms of Use - User Information Legal Enquiry Guide</p>
                <p class="text-muted"> &copy 2019 Company name, All rights reserved </p>
                <br>
            </section>
        </div><!-- //container -->
    </footer>



</body>
</html>